[package]
name = "input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true, features = ["rt", "sync"] }
tracing = { workspace = true }
evdev = { version = "0.12", features = ["tokio"] }
futures-util = { workspace = true }
fixed-map = { workspace = true }
