[package]
name = "audio"
version = "0.1.0"
edition = "2021"

[build-dependencies]
build = { path = "../build" }
bindgen = "0.69.4"

[dependencies]
nix = { workspace = true }
tracing = { workspace = true }
