[build]
target = "armv7-unknown-linux-gnueabihf"
rustflags = [
	"-C", "target-cpu=cortex-a7",
	"-Z", "threads=8"
]

[target.armv7-unknown-linux-gnueabihf]
linker = "./tools/bin/oxide-cc"

[env]
OXIDE_ROOT = { value = "", relative = true, force = true }
CC_armv7_unknown_linux_gnueabihf = { value = "tools/bin/oxide-cc", relative = true, force = true }
CXX_armv7_unknown_linux_gnueabihf = { value = "tools/bin/oxide-cxx", relative = true, force = true }
RUSTC_LINKER = { value = "tools/bin/oxide-cc", relative = true, force = true }
PKG_CONFIG_SYSROOT_DIR = { value = "build/sysroot", relative = true, force = true }
PKG_CONFIG_PATH = { value = "build/sysroot/usr/lib/arm-linux-gnueabihf/pkgconfig", relative = true, force = true }
