[package]
name = "launch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true, features = ["rt", "fs", "parking_lot"] }
thiserror = { workspace = true }
futures-util = { workspace = true }
miyoo-mini-hal = { path = "../miyoo-mini-hal" }
