[package]
name = "ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { workspace = true, default-features = false, features = ["tokio", "debug"] }
shared-ui = { path = "../shared-ui" }
tokio = { workspace = true, features = ["sync"] }
futures-util = "0.3.28"
system = { path = "../system" }
input = { path = "../input" }
tracing = { workspace = true }
once_cell = { workspace = true, features = ["parking_lot"] }
parking_lot = { workspace = true }
miyoo-mini-hal = { path = "../miyoo-mini-hal" }
