[package]
name = "miyoo-mini-hal"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["sync", "process", "parking_lot"] }
tokio-gpiod = { version = "0.2.3", default-features = false }
tokio-sysfs-pwm = { path = "../tokio-sysfs-pwm" }
i2cdev = "0.5.1"
once_cell = { version = "1.17.1", features = ["parking_lot"] }
parking_lot = "0.12.1"
