[package]
name = "miyoo-mini-hal"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["sync", "process", "parking_lot"] }
tokio-sysfs-pwm = { path = "../tokio-sysfs-pwm" }
i2cdev = "0.5.1"
once_cell = { workspace = true, features = ["parking_lot"] }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
