[package]
name = "os"
version = "0.0.1"
edition = "2021"

[build-dependencies]
build = { path = "../build" }

[dependencies]
tokio = { workspace = true, features = ["rt", "time", "macros", "parking_lot"] }
tracing = { workspace = true }
mimalloc = { workspace = true, default-features = false }
nix = { workspace = true, features = ["fs"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
launch = { path = "../launch" }
miyoo-mini-hal = { path = "../miyoo-mini-hal" }
input = { path = "../input" }
ui = { path = "../ui" }
