[package]
name = "compositor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
smithay-drm-extras = { git = "https://github.com/Smithay/smithay.git", rev = "858ed62" }
framebuffer = "0.3.1"
mimalloc = { version = "0.1.37", default-features = false }

[dependencies.smithay]
git = "https://github.com/Smithay/smithay.git"
rev = "858ed62"
default-features = false
features = ["backend_x11", "backend_udev", "backend_drm", "renderer_gl", "wayland_frontend"]
