[package]
name = "system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true, features = ["rt", "time", "macros", "parking_lot"] }
tracing = { workspace = true }
nix = { version = "0.26.2", features = ["fs"] }
launch = { path = "../launch" }
miyoo-mini-hal = { path = "../miyoo-mini-hal" }
input = { path = "../input" }
